# fly.toml file generated for restless-field-1898 on 2022-03-10T13:32:34-07:00

app = "%fly_app_name%-redis"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]
  REDIS_PASSWORD = "%fly_redis_password%"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  port = 9091
  path = "/metrics"
